<?php

use Illuminate\Database\Seeder;

class Braceletgears extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $param =     [
                   
[
    "item_name"=>"エデンモーン・アタッカーリストレット",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"モンク 竜騎士 侍",
    "equipable_job_name"=>"mnk drg sam",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"158",
    "dir_status"=>"226",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/3534f0df8d2/"],
    [
    "item_name"=>"エデンモーン・キャスターリストレット",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"黒魔道士 召喚士 赤魔道士 青魔道士",
    "equipable_job_name"=>"blm smn rdm mlu",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/c7caf8506a4/"],
    [
    "item_name"=>"エデンモーン・ディフェンダーリストレット",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"ナイト 戦士 暗黒騎士 ガンブレイカー",
    "equipable_job_name"=>"pld war drk gnb",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"158",
    "dir_status"=>"0",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"226",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/3493dd3d5fa/"],
    [
    "item_name"=>"エデンモーン・ヒーラーリストレット",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"白魔道士 学者 占星術師",
    "equipable_job_name"=>"whm sch ast",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"226",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"158",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/fc8c6e08ebf/"],
    [
    "item_name"=>"エデンモーン・レンジャーリストレット",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"吟遊詩人 忍者 機工士 踊り子",
    "equipable_job_name"=>"brd nin mcn dnc",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"158",
    "dir_status"=>"0",
    "det_status"=>"226",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/9b46bbd589e/"],
    [
    "item_name"=>"クリプトラーカー・アタッカーブレスレットRE",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"モンク 竜騎士 侍",
    "equipable_job_name"=>"mnk drg sam",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"226",
    "sks_status"=>"158",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/54d5b925b5a/"],
    [
    "item_name"=>"クリプトラーカー・キャスターブレスレットRE",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"黒魔道士 召喚士 赤魔道士 青魔道士",
    "equipable_job_name"=>"blm smn rdm mlu",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"0",
    "dir_status"=>"226",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"158",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/f6fdceabbd5/"],
    [
    "item_name"=>"クリプトラーカー・ディフェンダーブレスレットRE",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"ナイト 戦士 暗黒騎士 ガンブレイカー",
    "equipable_job_name"=>"pld war drk gnb",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"226",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/92affbc82d7/"],
    [
    "item_name"=>"クリプトラーカー・ヒーラーブレスレットRE",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"白魔道士 学者 占星術師",
    "equipable_job_name"=>"whm sch ast",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"158",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/4ed756d2af8/"],
    [
    "item_name"=>"クリプトラーカー・レンジャーブレスレットRE",
    "location"=>"腕輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"吟遊詩人 忍者 機工士 踊り子",
    "equipable_job_name"=>"brd nin mcn dnc",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"226",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/eaf759eb6aa/"],
    
    
    
        ];


        DB::table('braceletgears')->insert($param);
    }
}
