<?php

use Illuminate\Database\Seeder;

class Earringgears extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $param =     [
                   
[
    "item_name"=>"エデンモーン・アタッカーイヤリング",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"モンク 竜騎士 侍",
    "equipable_job_name"=>"mnk drg sam",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"226",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/5a15cd41441/"],
    [
    "item_name"=>"エデンモーン・キャスターイヤリング",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"黒魔道士 召喚士 赤魔道士 青魔道士",
    "equipable_job_name"=>"blm smn rdm blu",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/373d2e88b3a/"],
    [
    "item_name"=>"エデンモーン・ディフェンダーイヤリング",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"ナイト 戦士 暗黒騎士 ガンブレイカー",
    "equipable_job_name"=>"pld war drk gnb",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"0",
    "sks_status"=>"226",
    "sps_status"=>"0",
    "ten_status"=>"158",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/5ee6937148a/"],
    [
    "item_name"=>"エデンモーン・ヒーラーイヤリング",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"白魔道士 学者 占星術師",
    "equipable_job_name"=>"whm sch ast",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"158",
    "dir_status"=>"0",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"226",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/5cbff67f6d0/"],
    [
    "item_name"=>"エデンモーン・レンジャーイヤリング",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"吟遊詩人 忍者 機工士 踊り子",
    "equipable_job_name"=>"brd nin mcn dnc",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/155b793915c/"],
    [
    "item_name"=>"クリプトラーカー・アタッカーイヤリングRE",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"モンク 竜騎士 侍",
    "equipable_job_name"=>"mnk drg sam",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"158",
    "dir_status"=>"226",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/42678e75935/"],
    [
    "item_name"=>"クリプトラーカー・キャスターイヤリングRE",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"黒魔道士 召喚士 赤魔道士 青魔道士",
    "equipable_job_name"=>"blm smn rdm blu",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"0",
    "dir_status"=>"226",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"158",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/d9ffd0d6461/"],
    [
    "item_name"=>"クリプトラーカー・ディフェンダーイヤリングRE",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"ナイト 戦士 暗黒騎士 ガンブレイカー",
    "equipable_job_name"=>"pld war drk gnb",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/ed195c0466f/"],
    [
    "item_name"=>"クリプトラーカー・ヒーラーイヤリングRE",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"白魔道士 学者 占星術師",
    "equipable_job_name"=>"whm sch ast",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"158",
    "dir_status"=>"0",
    "det_status"=>"226",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/5508c1d113a/"],
    [
    "item_name"=>"クリプトラーカー・レンジャーイヤリングRE",
    "location"=>"耳飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"吟遊詩人 忍者 機工士 踊り子",
    "equipable_job_name"=>"brd nin mcn dnc",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"226",
    "sks_status"=>"158",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/3648be317fc/"],
    
    
    
        ];


        DB::table('earringgears')->insert($param);
    }
}
