<?php

use Illuminate\Database\Seeder;

class Foods extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $param = [

            [
                "item_name"=>"---",
                "location"=>"食事",
                "item_level"=>"0",
                "vit_status"=>"0",
                "vit_status_limit"=>"0",
                "crt_status"=>"0",
                "crt_status_limit"=>"0",
                "dir_status"=>"0",
                "dir_status_limit"=>"0",
                "det_status"=>"0",
                "det_status_limit"=>"0",
                "sks_status"=>"0",
                "sks_status_limit"=>"0",
                "sps_status"=>"0",
                "sps_status_limit"=>"0",
                "ten_status"=>"10",
                "ten_status_limit"=>"0",
                "pie_status"=>"0",
                "pie_status_limit"=>"0",
                "image"=>"0",
                "url"=>" ",
                "text"=>"---"],
            
            
    [
    "item_name"=>"ピッツァ(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"0",
    "crt_status_limit"=>"0",
    "dir_status"=>"10",
    "dir_status_limit"=>"179",
    "det_status"=>"10",
    "det_status_limit"=>"108",
    "sks_status"=>"0",
    "sks_status_limit"=>"0",
    "sps_status"=>"0",
    "sps_status_limit"=>"0",
    "ten_status"=>"0",
    "ten_status_limit"=>"0",
    "pie_status"=>"0",
    "pie_status_limit"=>"0",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/bc2468db942/",
    "text"=>"薄く延ばした生地に、トマトペーストとチーズを載せて焼き上げた料理経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    [
    "item_name"=>"ミストスピナッチキッシュ(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"0",
    "crt_status_limit"=>"0",
    "dir_status"=>"10",
    "dir_status_limit"=>"108",
    "det_status"=>"0",
    "det_status_limit"=>"0",
    "sks_status"=>"10",
    "sks_status_limit"=>"179",
    "sps_status"=>"0",
    "sps_status_limit"=>"0",
    "ten_status"=>"0",
    "ten_status_limit"=>"0",
    "pie_status"=>"0",
    "pie_status_limit"=>"0",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/7061a53f111/",
    "text"=>"パイ生地で作った器に、ミストスピナッチとチーズを乗せて焼き上げた料理経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    [
    "item_name"=>"チキンフェットゥチーネ(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"10",
    "crt_status_limit"=>"179",
    "dir_status"=>"0",
    "dir_status_limit"=>"0",
    "det_status"=>"0",
    "det_status_limit"=>"0",
    "sks_status"=>"10",
    "sks_status_limit"=>"108",
    "sps_status"=>"0",
    "sps_status_limit"=>"0",
    "ten_status"=>"0",
    "ten_status_limit"=>"0",
    "pie_status"=>"0",
    "pie_status_limit"=>"0",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/82236739962/",
    "text"=>"クリームソースに地鶏のモモ肉を和えたパスタ経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    [
    "item_name"=>"スモークチキン(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"10",
    "crt_status_limit"=>"108",
    "dir_status"=>"0",
    "dir_status_limit"=>"0",
    "det_status"=>"10",
    "det_status_limit"=>"179",
    "sks_status"=>"0",
    "sks_status_limit"=>"0",
    "sps_status"=>"0",
    "sps_status_limit"=>"0",
    "ten_status"=>"0",
    "ten_status_limit"=>"0",
    "pie_status"=>"0",
    "pie_status_limit"=>"0",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/ee851a0fcfc/",
    "text"=>"地鶏のモモ肉をじっくり燻製にした料理経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    [
    "item_name"=>"ゴールドパインジュース(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"0",
    "crt_status_limit"=>"0",
    "dir_status"=>"0",
    "dir_status_limit"=>"0",
    "det_status"=>"10",
    "det_status_limit"=>"108",
    "sks_status"=>"0",
    "sks_status_limit"=>"0",
    "sps_status"=>"0",
    "sps_status_limit"=>"0",
    "ten_status"=>"0",
    "ten_status_limit"=>"0",
    "pie_status"=>"10",
    "pie_status_limit"=>"179",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/46318bf17a6/",
    "text"=>"ゴールドパインを絞ったフレッシュジュース経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    [
    "item_name"=>"パインサラダ(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"0",
    "crt_status_limit"=>"0",
    "dir_status"=>"0",
    "dir_status_limit"=>"0",
    "det_status"=>"0",
    "det_status_limit"=>"0",
    "sks_status"=>"0",
    "sks_status_limit"=>"0",
    "sps_status"=>"10",
    "sps_status_limit"=>"179",
    "ten_status"=>"0",
    "ten_status_limit"=>"0",
    "pie_status"=>"10",
    "pie_status_limit"=>"108",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/bc484b2b47a/",
    "text"=>"フラントーヨオイルで味を調えたゴールドパインのサラダ経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    [
    "item_name"=>"ゼフィール(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"0",
    "crt_status_limit"=>"0",
    "dir_status"=>"10",
    "dir_status_limit"=>"108",
    "det_status"=>"0",
    "det_status_limit"=>"0",
    "sks_status"=>"0",
    "sks_status_limit"=>"0",
    "sps_status"=>"10",
    "sps_status_limit"=>"179",
    "ten_status"=>"0",
    "ten_status_limit"=>"0",
    "pie_status"=>"0",
    "pie_status_limit"=>"0",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/728726b13a6/",
    "text"=>"トワイライトアップルのピューレを使った柔らかな菓子経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    [
    "item_name"=>"アップルポポトサラダ(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"10",
    "crt_status_limit"=>"179",
    "dir_status"=>"0",
    "dir_status_limit"=>"0",
    "det_status"=>"0",
    "det_status_limit"=>"0",
    "sks_status"=>"0",
    "sks_status_limit"=>"0",
    "sps_status"=>"10",
    "sps_status_limit"=>"108",
    "ten_status"=>"0",
    "ten_status_limit"=>"0",
    "pie_status"=>"0",
    "pie_status_limit"=>"0",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/c50d9bbb3ce/",
    "text"=>"刻んだトワイライトアップルを加えたポポトサラダ経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    [
    "item_name"=>"レモンマフィン(HQ)",
    "location"=>"食事",
    "item_level"=>"510",
    "vit_status"=>"10",
    "vit_status_limit"=>"260",
    "crt_status"=>"0",
    "crt_status_limit"=>"0",
    "dir_status"=>"0",
    "dir_status_limit"=>"0",
    "det_status"=>"10",
    "det_status_limit"=>"179",
    "sks_status"=>"0",
    "sks_status_limit"=>"0",
    "sps_status"=>"0",
    "sps_status_limit"=>"0",
    "ten_status"=>"10",
    "ten_status_limit"=>"108",
    "pie_status"=>"0",
    "pie_status_limit"=>"0",
    "image"=>"0",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/58661f5b4a2/",
    "text"=>"リトルレモンを混ぜた生地を焼き上げたマフィン経験値獲得量 +3%効果時間 30:00[最大2倍まで効果時間の継ぎ足し可能]"],
    
    
        ];
        
        DB::table('foods')->insert($param);

    }
}
