<?php

use Illuminate\Database\Seeder;

class Necklacegears extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $param =     [
                   
[
    "item_name"=>"エデンモーン・アタッカーチョーカー",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"モンク 竜騎士 侍",
    "equipable_job_name"=>"mnk drg sam",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/3ab4ec499ae/"],
    [
    "item_name"=>"エデンモーン・キャスターチョーカー",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"黒魔道士 召喚士 赤魔道士 青魔道士",
    "equipable_job_name"=>"blm smn rdm mlu",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"158",
    "dir_status"=>"0",
    "det_status"=>"226",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/41332557292/"],
    [
    "item_name"=>"エデンモーン・ディフェンダーチョーカー",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"ナイト 戦士 暗黒騎士 ガンブレイカー",
    "equipable_job_name"=>"pld war drk gnb",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"158",
    "dir_status"=>"0",
    "det_status"=>"226",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/54ad201be04/"],
    [
    "item_name"=>"エデンモーン・ヒーラーチョーカー",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"白魔道士 学者 占星術師",
    "equipable_job_name"=>"whm sch ast",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"226",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/639043f00b1/"],
    [
    "item_name"=>"エデンモーン・レンジャーチョーカー",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"吟遊詩人 忍者 機工士 踊り子",
    "equipable_job_name"=>"brd nin mcn dnc",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"158",
    "det_status"=>"226",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/300299668cc/"],
    [
    "item_name"=>"クリプトラーカー・アタッカーチョーカーRE",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"モンク 竜騎士 侍",
    "equipable_job_name"=>"mnk drg sam",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"158",
    "det_status"=>"226",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/ed5cbb150b8/"],
    [
    "item_name"=>"クリプトラーカー・キャスターチョーカーRE",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"黒魔道士 召喚士 赤魔道士 青魔道士",
    "equipable_job_name"=>"blm smn rdm mlu",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"0",
    "dir_status"=>"158",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"226",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/c61fae529f4/"],
    [
    "item_name"=>"クリプトラーカー・ディフェンダーチョーカーRE",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"ナイト 戦士 暗黒騎士 ガンブレイカー",
    "equipable_job_name"=>"pld war drk gnb",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"226",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/5eb60ccc32c/"],
    [
    "item_name"=>"クリプトラーカー・ヒーラーチョーカーRE",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"白魔道士 学者 占星術師",
    "equipable_job_name"=>"whm sch ast",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"158",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/7326a185262/"],
    [
    "item_name"=>"クリプトラーカー・レンジャーチョーカーRE",
    "location"=>"首飾り",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"吟遊詩人 忍者 機工士 踊り子",
    "equipable_job_name"=>"brd nin mcn dnc",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"0",
    "sks_status"=>"158",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/32ef49b392f/"],
    
    
    
        ];


        DB::table('necklacegears')->insert($param);
    }
}
