<?php

use Illuminate\Database\Seeder;

class Races extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $param =     [
                
                [
                "race_clan"=>"---",
                "str"=>"0",
                "dex"=>"0",
                "vit"=>"0",
                "int"=>"0",
                "mnd"=>"0",
                "name"=>"non"],
                [
                "race_clan"=>"ヒュラ：ミッドランダー",
                "str"=>"22",
                "dex"=>"19",
                "vit"=>"20",
                "int"=>"23",
                "mnd"=>"19",
                "name"=>"mid"],
                [
                "race_clan"=>"ヒュラ：ハイランダー",
                "str"=>"23",
                "dex"=>"20",
                "vit"=>"22",
                "int"=>"18",
                "mnd"=>"20",
                "name"=>"hig"],
                [
                "race_clan"=>"ミコ：サンシーカー",
                "str"=>"22",
                "dex"=>"23",
                "vit"=>"20",
                "int"=>"19",
                "mnd"=>"19",
                "name"=>"sun"],
                [
                "race_clan"=>"ミコ：ムーンキーパー",
                "str"=>"19",
                "dex"=>"22",
                "vit"=>"18",
                "int"=>"21",
                "mnd"=>"23",
                "name"=>"moo"],
                [
                "race_clan"=>"ララ：プレーンフォーク",
                "str"=>"19",
                "dex"=>"23",
                "vit"=>"19",
                "int"=>"22",
                "mnd"=>"20",
                "name"=>"pla"],
                [
                "race_clan"=>"ララ：デューンフォーク",
                "str"=>"19",
                "dex"=>"21",
                "vit"=>"18",
                "int"=>"22",
                "mnd"=>"23",
                "name"=>"dun"],
                [
                "race_clan"=>"エレ：フォレスター",
                "str"=>"20",
                "dex"=>"23",
                "vit"=>"19",
                "int"=>"22",
                "mnd"=>"19",
                "name"=>"for"],
                [
                "race_clan"=>"エレ：シェーダー",
                "str"=>"20",
                "dex"=>"20",
                "vit"=>"19",
                "int"=>"23",
                "mnd"=>"21",
                "name"=>"sha"],
                [
                "race_clan"=>"ルガ：ゼーヴォルフ",
                "str"=>"22",
                "dex"=>"19",
                "vit"=>"23",
                "int"=>"18",
                "mnd"=>"21",
                "name"=>"see"],
                [
                "race_clan"=>"ルガ：ローエンガルデ",
                "str"=>"20",
                "dex"=>"18",
                "vit"=>"23",
                "int"=>"20",
                "mnd"=>"22",
                "name"=>"loh"],
                [
                "race_clan"=>"アウラ；アウラ・レン",
                "str"=>"19",
                "dex"=>"22",
                "vit"=>"19",
                "int"=>"20",
                "mnd"=>"23",
                "name"=>"rae"],
                [
                "race_clan"=>"アウラ；アウラ・ゼラ",
                "str"=>"23",
                "dex"=>"20",
                "vit"=>"22",
                "int"=>"20",
                "mnd"=>"18",
                "name"=>"xae"],
                [
                "race_clan"=>"ヴィエラ：ラヴァ・ヴィエラ",
                "str"=>"20",
                "dex"=>"23",
                "vit"=>"18",
                "int"=>"21",
                "mnd"=>"21",
                "name"=>"rav"],
                [
                "race_clan"=>"ヴィエラ：ヴィナ・ヴィエラ",
                "str"=>"19",
                "dex"=>"20",
                "vit"=>"19",
                "int"=>"23",
                "mnd"=>"22",
                "name"=>"vee"],
                [
                "race_clan"=>"ロスガル：ヘリオン",
                "str"=>"23",
                "dex"=>"17",
                "vit"=>"23",
                "int"=>"17",
                "mnd"=>"23",
                "name"=>"hel"],
                [
                "race_clan"=>"ロスガル：ロスト",
                "str"=>"23",
                "dex"=>"17",
                "vit"=>"23",
                "int"=>"17",
                "mnd"=>"23",
                "name"=>"los"],     
        ];

        DB::table('races')->insert($param);
    }
}
