<?php

use Illuminate\Database\Seeder;

class Ringgears extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $param =     [
                   
[
    "item_name"=>"エデンモーン・アタッカーリング",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"モンク 竜騎士 侍",
    "equipable_job_name"=>"mnk drg sam",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/ffcacbe9163/"],
    [
    "item_name"=>"エデンモーン・キャスターリング",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"黒魔道士 召喚士 赤魔道士 青魔道士",
    "equipable_job_name"=>"blm smn rdm mlu",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"0",
    "dir_status"=>"158",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"226",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/ad89589476f/"],
    [
    "item_name"=>"エデンモーン・ディフェンダーリング",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"ナイト 戦士 暗黒騎士 ガンブレイカー",
    "equipable_job_name"=>"pld war drk gnb",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/cfdb23c1e43/"],
    [
    "item_name"=>"エデンモーン・ヒーラーリング",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"白魔道士 学者 占星術師",
    "equipable_job_name"=>"whm sch ast",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"226",
    "dir_status"=>"0",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"158",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/9bdaeafdb21/"],
    [
    "item_name"=>"エデンモーン・レンジャーリング",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"吟遊詩人 忍者 機工士 踊り子",
    "equipable_job_name"=>"brd nin mcn dnc",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"226",
    "dir_status"=>"158",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/fb6f0663f77/"],
    [
    "item_name"=>"クリプトラーカー・アタッカーリングRE",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"モンク 竜騎士 侍",
    "equipable_job_name"=>"mnk drg sam",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"158",
    "dir_status"=>"226",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/0bfa25d44f6/"],
    [
    "item_name"=>"クリプトラーカー・キャスターリングRE",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"黒魔道士 召喚士 赤魔道士 青魔道士",
    "equipable_job_name"=>"blm smn rdm mlu",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"226",
    "dir_status"=>"158",
    "det_status"=>"0",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/860e7b3a0e4/"],
    [
    "item_name"=>"クリプトラーカー・ディフェンダーリングRE",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"ナイト 戦士 暗黒騎士 ガンブレイカー",
    "equipable_job_name"=>"pld war drk gnb",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"0",
    "sks_status"=>"158",
    "sps_status"=>"0",
    "ten_status"=>"226",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/6e88bd25ab4/"],
    [
    "item_name"=>"クリプトラーカー・ヒーラーリングRE",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"白魔道士 学者 占星術師",
    "equipable_job_name"=>"whm sch ast",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"320",
    "crt_status"=>"0",
    "dir_status"=>"0",
    "det_status"=>"158",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"226",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/d44e65186ce/"],
    [
    "item_name"=>"クリプトラーカー・レンジャーリングRE",
    "location"=>"指輪",
    "item_level"=>"530",
    "physical_p"=>"0",
    "auto_attack"=>"0",
    "attack_interval"=>"0",
    "defense"=>"1",
    "m_defense"=>"1",
    "equipable_job"=>"吟遊詩人 忍者 機工士 踊り子",
    "equipable_job_name"=>"brd nin mcn dnc",
    "equipable_level"=>"80",
    "main_status"=>"310",
    "vit_status"=>"356",
    "crt_status"=>"158",
    "dir_status"=>"0",
    "det_status"=>"226",
    "sks_status"=>"0",
    "sps_status"=>"0",
    "ten_status"=>"0",
    "pie_status"=>"0",
    "materia01"=>"1",
    "materia02"=>"1",
    "materia03"=>"0",
    "materia04"=>"0",
    "materia05"=>"0",
    "max_status"=>"226",
    "dup"=>"0",
    "image"=>"",
    "url"=>"https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/adc2f13dcf2/"],
    
    
    
        ];


        DB::table('ringgears')->insert($param);
    }
}
